# Generated by Django 3.2.6 on 2021-08-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128)),
                ('trailer', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
