# Generated by Django 3.2.6 on 2021-08-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_mocie_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='mocie_images',
            new_name='movie_images',
        ),
    ]
