# Generated by Django 3.2.6 on 2021-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_borrowed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
